default:
	cd makeprocs; make
	cd hello_world; make
	cd beyond_max; make
	cd beyond_allocated; make
	cd grow_stack; make

clean:
	cd makeprocs; make clean
	cd hello_world; make clean
	cd beyond_max; make clean
	cd beyond_allocated; make clean
	cd grow_stack; make clean

# run:
# 	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 5; ee469_fixterminal
